spring.application.name=gestiondessalles
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_salle
spring.datasource.username=postgres
spring.datasource.password=projTD
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
